### ISSUE TITLE
Issue about step 2- Run ICRA

### ISSUE THREAD

**Issue by priforemma** [korem-lab/SGVFinder2#15]
After creating DB, I got four files .dests .dlen .fasta .lengths. But I got an error in the step2 RUN ICRA: Command 'bowtie2 -x /data/database/test_db -U /data/reads/1.fa --very-sensitive -k 20  --quiet -p 1 | samtools view -bS -@ 0 - > /data/map_test/1.fa.bam' returned non-zero exit status 1. 
So I run this command. But there's still an error.
Could not locate a Bowtie index corresponding to basename "/data/database/test_db"
Error: Encountered internal Bowtie 2 exception (#1)
i'm sure there are fours files in /data/database (test_db.dests .dlen .length .fasta).

I need your help,thanks.

**Comment by talkorem** [comment]
You need to create a bowtie index.
Run `bowtie2-build test_db.fasta test_db`

**Comment by priforemma** [comment]
> You need to create a bowtie index. Run `bowtie2-build test_db.fasta test_db`

thanks,I've solved it.😀
