### ISSUE TITLE
ICRA

### ISSUE THREAD

**Issue by treasure316** [korem-lab/SGVFinder2#2]
Hello, I want to use shell to run ICRA step, how should the code be written?
Looking forward to your reply.
Best wishes!

**Comment by treasure316** [comment]
I also got an error when I tried to run the code to verify that the installation was successful

python /home/worker017/.conda/envs/SGV2/lib/python3.10/site-packages/SGVFinder2/helpers/SGVF_PerFile_cmd.py --help
Traceback (most recent call last):
  File "/home/worker017/.conda/envs/SGV2/lib/python3.10/site-packages/SGVFinder2/helpers/SGVF_PerFile_cmd.py", line 1, in <module>
    from SGVFinder import get_sample_map
ModuleNotFoundError: No module named 'SGVFinder'

**Comment by ym2877** [comment]
Hi @treasure316, thank you for submitting this issue!

If you are getting an error when running 'import' that means you have not installed the package correctly. Also, I will note that the correct import would be `from SGVFinder2 import get_sample_map`. Try following these steps to install this package in a new conda environment-

1. Create conda environment with `conda create -n sgvfinder2 python=3.10 lightgbm`
2. Activate new environment with `conda activate sgvfinder2`
3. Install package with `pip install --no-cache-dir git+https://github.com/korem-lab/SGVFinder2.git`

After running through these steps, I'd double-check to make sure you have all the following dependencies installed. If any are missing, you can install them independently with `conda` or `pip`.
    - python (tested with 3.10.12)
    - numpy (tested with 1.26.0)
    - pandas (tested with 2.1.0)
    - Cython (tested with 3.0.2)
    - ujson (tested with 5.8.0)
    - pysam (tested with 0.21.0)
    - scipy (tested with 1.11.2)
    - bokeh (tested with 3.2.2)
    - Bio (tested with 1.5.9)
    - bowtie2 (tested with 2.2.5)

We do not have command line functionality working as of right now, but this is next on my TODO list. In the meantime, you can run ICRA from a python environment (either a notebook or script) as shown in `workflow.ipynb`. Please don't hesitate to reach out if you have any further questions!

**Comment by treasure316** [comment]
Hello, thank you for your reply

Part has been run successfully in front of me, but it is still an error as follows, could you tell me what is the problem?

**Comment by treasure316** [comment]
Hello, thank you for your reply

Part has been run successfully in front of me, but it is still an error as follows, could you tell me what is the problem?

**Comment by treasure316** [comment]
Hello, thank you for your reply

Part has been run successfully in front of me, but it is still an error as follows, could you tell me what is the problem?                  $ python /mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/SGVF_PerFile_cmd.py --help
Traceback (most recent call last):
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/SGVF_PerFile_cmd.py", line 1, in <module>
    from SGVFinder import get_sample_map
ModuleNotFoundError: No module named 'SGVFinder'

**Comment by treasure316** [comment]
This is my environment configuration
(SGV_2) worker018@dell-PowerEdge-R740-28:/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25$ bowtie2 --version
/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/bin/bowtie2-align-s version 2.2.5
64-bit
Built on localhost.localdomain
Thu Mar  5 18:34:52 EST 2015
Compiler: gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)
Options: -O3 -m64 -msse2  -funroll-loops -g3 -DPOPCNT_CAPABILITY
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
(SGV_2) worker018@dell-PowerEdge-R740-28:/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25$ pip list
Package            Version
------------------ ------------
bio                1.5.9
biopython          1.81
biothings-client   0.3.1
bokeh              3.2.2
certifi            2023.11.17
charset-normalizer 3.3.2
contourpy          1.2.0
Cython             3.0.2
gprofiler-official 1.0.0
idna               3.6
Jinja2             3.1.2
MarkupSafe         2.1.3
mygene             3.2.2
numpy              1.26.2
packaging          23.2
pandas             2.1.3
Pillow             10.1.0
pip                23.3.1
platformdirs       4.0.0
pooch              1.8.0
pysam              0.21.0
python-dateutil    2.8.2
pytz               2023.3.post1
PyYAML             6.0.1
requests           2.31.0
scipy              1.11.4
setuptools         68.2.2
SGVFinder2         0.0.1
six                1.16.0
tornado            6.4
tqdm               4.66.1
tzdata             2023.3
ujson              5.8.0
urllib3            2.1.0
wheel              0.41.3
xyzservices        2023.10.1

**Comment by treasure316** [comment]
Hello, thank you very much for your reply.If I want to analyze data with Sgvfinder2, do I need to run it with the workflow.ipynb file? Does this file need to be run in python? Sorry I'm not familiar with python, but if I want to run it in linux, save it directly as a py file and run it in Python workflow.py.

**Comment by ym2877** [comment]
The `workflow.ipynb` notebook is just there to serve as an example of how you would run each step of this pipeline, it is by no means required. More than anything, it is a good way of ensuring that you have the package installed correctly and that each step is running properly. 

You could theoretically do what you said (running it as a python file), but I would suggest doing so on each step separately.

**Comment by treasure316** [comment]
Ok, I'll try again. Thank you very much.

**Comment by ym2877** [comment]
Also @treasure316 ,

Make sure you have bowtie2 installed as well with `conda install -c bioconda bowtie2`

**Comment by treasure316** [comment]
Hi!

**Comment by treasure316** [comment]
I installed the  bowtie2 using the following code:
cd /mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/bin
wget https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.2.5/bowtie2-2.2.5-linux-x86_64.zip
unzip bowtie2-2.2.5-linux-x86_64.zip
$bowtie2 --version
/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/bin/bowtie2-align-s version 2.2.5
64-bit
Built on localhost.localdomain
Thu Mar  5 18:34:52 EST 2015
Compiler: gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)
Options: -O3 -m64 -msse2  -funroll-loops -g3 -DPOPCNT_CAPABILITY
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}

I tried to save the workflow.ipynb to a .py file and run it with python work.py. 
**#STEP1 run workflow_db.py**
python /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_db.py

The contents of the workflow_db.py is as follows.
from SGVFinder2 import create_db_from_reps

#db path /mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/db
#   input_path   must be folder containing one fasta file per genome. Files need to end with either fasta, fasta.gz, fa, or fa.gz
create_db_from_reps(
    input_path='/mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/hg19/',
    out_prefix='my_custom_db'
)

Output the **four files** in  /mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/db .



**#STEP 2 ICRA**
cd /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/result/
mkdir -p sgv2/icra
cd sgv2/icra
$ python /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_icra.py
Creating directory example_out/...
Running ICRA on paired-end reads!
Forward- /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_1.fastq
Reverse- /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_1.fastq
--------------------------------------------

Traceback (most recent call last):
  File "/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_icra.py", line 13, in <module>
    jspi_file, jsdel_file = single_file(
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 86, in single_file
    sam2pmp(outpref + '.bam', outpref + '.pmp', full=True)
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/ICRAUtils.py", line 23, in timed
    result = method(*args, **kw)
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/sam2pmp.py", line 22, in sam2pmp
    f = pysam.AlignmentFile(samfile)
  File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 996, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
(SGV_2) worker018@dell-PowerEdge-R740-28:/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/result/sgv2/icra$ python /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_icra.py
Running ICRA on paired-end reads!
Forward- /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_1.fastq
Reverse- /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_1.fastq
--------------------------------------------

example_out/SRR5273878.bam already exists, skipping mapping step...
Traceback (most recent call last):
  File "/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_icra.py", line 13, in <module>
    jspi_file, jsdel_file = single_file(
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 86, in single_file
    sam2pmp(outpref + '.bam', outpref + '.pmp', full=True)
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/ICRAUtils.py", line 23, in timed
    result = method(*args, **kw)
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/sam2pmp.py", line 22, in sam2pmp
    f = pysam.AlignmentFile(samfile)
  File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 996, in pysam.libcalignmentfile.AlignmentFile._open

**The contents of the **workflow_icra.py** is as follows.**
# 导入 SGVFinder2 库
from SGVFinder2 import single_file, get_sample_map
from pandas import to_pickle

# 定义输入文件路径
read1 = '/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_1.fastq'
read2 = '/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_1.fastq'

# 定义数据库路径
DATABASE = '/mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/db/'

# 运行 ICRA 程序
jspi_file, jsdel_file = single_file(
  fq1=read1,
  fq2=read2,
  outfol='example_out/',
  dbpath=DATABASE
)

# 获取样本映射表
sample_map = get_sample_map(jsdel_file, DATABASE+'.dlen')

# 保存样本映射表
to_pickle(sample_map, jsdel_file.replace('.jsdel','.smp'))

**Comment by ym2877** [comment]
Hi @treasure316 

Are you reads paired? If so, read2 should be `/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_2.fastq` as opposed to `/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_1.fastq` like you have it.

**Comment by treasure316** [comment]
Yes, my data is paired data. After I corrected the code related to the input data, I still got the following error. Is there a problem with the first step of database creation? Here is the content in my db folder. Please translate this to English.


**ERROR：**
(SGV_2) worker018@dell-PowerEdge-R740-28:/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/result/sgv2/icra$ python /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_icra.py
Running ICRA on paired-end reads!
Forward- /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_1.fastq
Reverse- /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_2.fastq
--------------------------------------------

example_out/SRR5273878.bam already exists, skipping mapping step...
Traceback (most recent call last):
  File "/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_icra.py", line 13, in <module>
    jspi_file, jsdel_file = single_file(
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 86, in single_file
    sam2pmp(outpref + '.bam', outpref + '.pmp', full=True)
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/ICRAUtils.py", line 23, in timed
    result = method(*args, **kw)
  File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/sam2pmp.py", line 22, in sam2pmp
    f = pysam.AlignmentFile(samfile)
  File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 996, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

**db content：**
my_custom_db.dests  1.9kb
my_custom_db.dlen  29b
my_custom_db.fasta  3GB
my_custom_db.lengths  2.3KB

**Comment by treasure316** [comment]
Yes, my data is paired data. After I corrected the code related to the input data, I still got the following error. Is there a problem with the first step of database creation? Here is the content in my db folder. Please translate this to English.

**ERROR**：
(SGV_2) worker018@dell-PowerEdge-R740-28:/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/result/sgv2/icra$ python /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_icra.py
Running ICRA on paired-end reads!
Forward- /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_1.fastq
Reverse- /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/SRR5273878_2.fastq
example_out/SRR5273878.bam already exists, skipping mapping step...
Traceback (most recent call last):
File "/mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_icra.py", line 13, in
jspi_file, jsdel_file = single_file(
File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 86, in single_file
sam2pmp(outpref + '.bam', outpref + '.pmp', full=True)
File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/ICRAUtils.py", line 23, in timed
result = method(*args, **kw)
File "/mnt/nfs/5110v5/xuexinxin/temp/yes/envs/SGV_2/lib/python3.10/site-packages/SGVFinder2/helpers/sam2pmp.py", line 22, in sam2pmp
f = pysam.AlignmentFile(samfile)
File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.cinit
File "pysam/libcalignmentfile.pyx", line 996, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False

**db content**：
my_custom_db.dests 1.9kb
my_custom_db.dlen 29b
my_custom_db.fasta 3GB
my_custom_db.lengths 2.3KB

**Comment by ym2877** [comment]
Hi @treasure316

From what I cant tell, it doesn't look like the database was built correctly. The folder should contain several .bt2I files, which are files that bowtie2 creates during indexing. If possible can you send me the code that you used to create your database?  

`create_db_from_reps` has a parameter **input_path** which must be folder containing one fasta file per genome. The files within this folder need to end with either fasta, fasta.gz, fa, or fa.gz.

**Comment by treasure316** [comment]
Hi @ym2877 
This is my code of create my database.
python /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_db.py

**workflow_db.py content:**
from SGVFinder2 import create_db_from_reps

#db path /mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/db
#   input_path   must be folder containing one fasta file per genome. Files need to end with either fasta, fasta.gz, fa, or fa.gz
create_db_from_reps(
    input_path='/mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/hg19/',
    out_prefix='my_custom_db'
)

**/mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/hg19/ content：**
hg19.fa  3GB

**Comment by treasure316** [comment]
Hi @ym2877
This is my code of create my database.
python /mnt/nfs/qnapNFS/jiangxin/cv/30001516_25/code/workflow_db.py

**workflow_db.py content:**
from SGVFinder2 import create_db_from_reps

#db path /mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/db

input_path must be folder containing one fasta file per genome. Files need to end with either fasta, fasta.gz, fa, or fa.gz
create_db_from_reps(
input_path='/mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/hg19/',
out_prefix='my_custom_db'
)

**/mnt/nfs/5110v5/jiangxin/code/SGV_finder_2/hg19/ content：**
hg19.fa 3GB

**Comment by talkorem** [comment]
Are you trying to build the reference for SVFinder from hg19? That is an odd use case and we've never benchmarked it.
In any case, you need to actually run the bowtie build command at after you finish with the create_db_from_reps.

**Comment by shentao1101** [comment]
Hello, I have encounter some problems when runing ICRA step:

(sgvfinder2) [shentao@slurm-m-01 prokaryotic]$ python runICRA.py 
Running ICRA on paired-end reads!
Forward- /hl/shentao/cleandata/Boar-s10.final_1.fastq.gz
Reverse- /hl/shentao/cleandata/Boar-s10.final_2.fastq.gz
--------------------------------------------

Traceback (most recent call last):
  File "/hl/shentao/refseq/prokaryotic/runICRA.py", line 8, in <module>
    jspi_file, jsdel_file = single_file(
  File "/hl/shentao/miniconda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/icra.py", line 79, in single_file
    do_pair_simple(fq1, fq2, outpref, indexf, senspreset, report_alns, max_ins, threads)
  File "/hl/shentao/miniconda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/Bowtie2WrapperSlim.py", line 25, in do_pair_simple
    dope(fq1, fq2, outprefix, indexf, True, False, senspreset, report_alns, 0, max_ins, True, True, False, False,
  File "/hl/shentao/miniconda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/Bowtie2WrapperSlim.py", line 51, in dope
    _ = _shell_command(cmd, loglevel=logging.DEBUG)
  File "/hl/shentao/miniconda3/envs/sgvfinder2/lib/python3.10/site-packages/SGVFinder2/helpers/ICRAUtils.py", line 95, in _shell_command
    errnout = sbcheck_output(com, shell=True, stderr=subprocess.STDOUT).decode(sys.stdout.encoding)
  File "/hl/shentao/miniconda3/envs/sgvfinder2/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/hl/shentao/miniconda3/envs/sgvfinder2/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bowtie2 -x /hl/shentao/refseq/prokaryotic/my_custom_db -1 /hl/shentao/cleandata/Boar-s10.final_1.fastq.gz -2 /hl/shentao/cleandata/Boar-s10.final_2.fastq.gz --very-sensitive -k 20  -I 0 -X 750 --no-mixed --no-discordant   --quiet -p 1 | samtools view -bS -@ 0 - > /hl/shentao/temp/icra/Boar-s10.final.bam' returned non-zero exit status 127.

I don't know what is the problem, so wish your help and reply, thanks!

**Comment by talkorem** [comment]
Can you please specify what bowtie and samtools versions you're running, and what you get when you try to run this directly:
bowtie2 -x /hl/shentao/refseq/prokaryotic/my_custom_db -1 /hl/shentao/cleandata/Boar-s10.final_1.fastq.gz -2 /hl/shentao/cleandata/Boar-s10.final_2.fastq.gz --very-sensitive -k 20 -I 0 -X 750 --no-mixed --no-discordant --quiet -p 1 | samtools view -bS -@ 0 - > /hl/shentao/temp/icra/Boar-s10.final.bam
